### ISSUE TITLE
Refactor main Constructs

### ISSUE THREAD

**Issue by cloudnautique** [rancher/terraform-controller#15]
Currently we have:

Modules
Executions -> tied to the plan existence of the output.
ExecutionRuns

This is missing something, a more durable construct that feels like the appropriate place to live on. Propose:
Modules
Environments -> Tied to the output of a module and it's variables. Essentially the long lived object that will own the TF State file.
Executions -> A long lived run of a plan.
Execution runs -> A run time environment that interacts with the final amalgamation of inputs and runs terraform. No state or persistence is to live on them.

**Comment by luthermonson** [comment]
Discussion with @cloudnautique and we're going to rename Executions > States and ExecutionRuns to Executions and see where that takes us.
